/**
 * iFlow Package Generator — Sprint 2
 * Generates a proper SAP Integration Suite importable ZIP package.
 *
 * Package structure:
 *   <IFlowName>.zip
 *   ├── META-INF/
 *   │   └── MANIFEST.MF
 *   └── src/main/resources/
 *       ├── scenarioflows/integrationflow/<iflow-id>.iflw   (BPMN2 XML)
 *       ├── parameters.prop                                   (externalized params)
 *       ├── mapping/<mapping-name>.mmap                       (if maps > 0)
 *       └── script/<script-name>.groovy                       (if scripting)
 */

const AdmZip = require('adm-zip');

// ── Main entry ────────────────────────────────────────────────────────────────

function generateIFlowPackage(artifact, platformData, conversionOutput) {
  const zip = new AdmZip();
  const iflowId   = buildIFlowId(artifact);
  const iflowName = buildIFlowName(artifact);
  const pkgName   = buildPackageName(artifact);

  // 1. MANIFEST.MF
  zip.addFile('META-INF/MANIFEST.MF', Buffer.from(buildManifest(iflowId, iflowName, pkgName, artifact)));

  // 2. Main iFlow BPMN2 XML
  const iflwXml = buildIFlowXML(artifact, platformData, conversionOutput, iflowId, iflowName);
  zip.addFile(`src/main/resources/scenarioflows/integrationflow/${iflowId}.iflw`, Buffer.from(iflwXml));

  // 3. parameters.prop — all externalized params
  zip.addFile('src/main/resources/parameters.prop', Buffer.from(buildParametersProp(artifact, platformData)));

  // 4. Message Mappings (.mmap) — one per map if maps_count > 0
  if ((artifact.maps_count || 0) > 0) {
    const maps = buildMessageMappings(artifact, platformData);
    maps.forEach(m => {
      zip.addFile(`src/main/resources/mapping/${m.filename}`, Buffer.from(m.content));
    });
  }

  // 5. Groovy scripts — stubs if artifact has scripting
  if (artifact.has_scripting) {
    const scripts = buildGroovyScripts(artifact, platformData);
    scripts.forEach(s => {
      zip.addFile(`src/main/resources/script/${s.filename}`, Buffer.from(s.content));
    });
  }

  return {
    buffer: zip.toBuffer(),
    filename: `${iflowId}_v1.0.zip`,
    iflowId,
    iflowName,
    packageName: pkgName
  };
}

// ── MANIFEST.MF ───────────────────────────────────────────────────────────────

function buildManifest(iflowId, iflowName, pkgName, artifact) {
  const now = new Date().toISOString().split('T')[0];
  return `Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: ${iflowName}
Bundle-SymbolicName: ${iflowId}
Bundle-Version: 1.0.0
Bundle-Vendor: Sierra Digital
Bundle-Description: Migrated from ${(artifact.platform || 'source').toUpperCase()} - ${artifact.name}
Created-By: IS Migration Tool (Sierra Digital)
Package-Name: ${pkgName}
artifact-type: IFlow
artifact-version: 1.0.0
Build-Timestamp: ${now}
Source-Platform: ${(artifact.platform || 'unknown').toUpperCase()}
Source-Artifact: ${artifact.name}
Domain: ${artifact.domain || 'INT'}
`;
}

// ── parameters.prop ───────────────────────────────────────────────────────────

function buildParametersProp(artifact, pd) {
  const platform = (artifact.platform || 'boomi').toLowerCase();
  const connTypes = pd.connectorTypes || pd.iflowAdapters || [];
  const lines = [
    `# Externalized Parameters — ${artifact.name}`,
    `# Generated by IS Migration Tool — Sierra Digital`,
    `# IMPORTANT: Update all {{PLACEHOLDER}} values before deploying to production`,
    `#`,
    `# Source Platform: ${platform.toUpperCase()}`,
    `# Domain: ${artifact.domain || 'INT'}`,
    `# Complexity: ${artifact.complexity_level || 'Medium'}`,
    ``
  ];

  // ── Sender / Trigger params
  const trigType = artifact.trigger_type || 'API';
  lines.push(`# --- Sender / Trigger ---`);
  if (trigType === 'API') {
    lines.push(`param.sender.address=/http/${buildIFlowId(artifact).toLowerCase().replace(/_/g, '-')}`);
    lines.push(`param.sender.auth.type=BasicAuthentication`);
    lines.push(`param.sender.user={{SENDER_USER}}`);
    lines.push(`param.sender.credential.alias={{SENDER_CREDENTIAL_ALIAS}}`);
  } else if (trigType === 'Schedule') {
    lines.push(`param.scheduler.cron=0 0 * * *`);
    lines.push(`param.scheduler.timezone=UTC`);
  } else if (trigType === 'Listener') {
    lines.push(`param.sftp.host={{SFTP_HOST}}`);
    lines.push(`param.sftp.port=22`);
    lines.push(`param.sftp.directory=/outbound/${artifact.domain?.toLowerCase() || 'data'}`);
    lines.push(`param.sftp.credential.alias={{SFTP_CREDENTIAL_ALIAS}}`);
  } else if (trigType === 'Event') {
    lines.push(`param.jms.connection.factory={{JMS_CONNECTION_FACTORY}}`);
    lines.push(`param.jms.queue.name={{JMS_QUEUE_NAME}}`);
    lines.push(`param.jms.credential.alias={{JMS_CREDENTIAL_ALIAS}}`);
  }
  lines.push(``);

  // ── Receiver / Target params — based on platform connector types
  lines.push(`# --- Receiver / Target System ---`);
  const primaryConnector = (artifact.primary_connector || 'HTTP').toUpperCase();
  if (primaryConnector.includes('SALESFORCE') || (connTypes || []).some(c => String(c).includes('Salesforce'))) {
    lines.push(`param.receiver.salesforce.address=https://{{SF_INSTANCE}}.salesforce.com`);
    lines.push(`param.receiver.salesforce.oauth.credential.alias={{SF_OAUTH_CREDENTIAL}}`);
  } else if (primaryConnector.includes('RFC') || (connTypes || []).some(c => String(c).includes('RFC'))) {
    lines.push(`param.receiver.sap.rfc.host={{SAP_HOST}}`);
    lines.push(`param.receiver.sap.rfc.system.number={{SAP_SYSNR}}`);
    lines.push(`param.receiver.sap.rfc.client={{SAP_CLIENT}}`);
    lines.push(`param.receiver.sap.credential.alias={{SAP_CREDENTIAL_ALIAS}}`);
  } else if ((connTypes || []).some(c => String(c).includes('IDoc'))) {
    lines.push(`param.receiver.idoc.sap.host={{SAP_HOST}}`);
    lines.push(`param.receiver.idoc.sap.client={{SAP_CLIENT}}`);
    lines.push(`param.receiver.idoc.sap.credential.alias={{SAP_CREDENTIAL_ALIAS}}`);
    lines.push(`param.receiver.idoc.port={{SAP_PORT}}`);
  } else if ((connTypes || []).some(c => String(c).includes('AS2'))) {
    lines.push(`param.receiver.as2.url={{AS2_PARTNER_URL}}`);
    lines.push(`param.receiver.as2.partner.id={{AS2_PARTNER_ID}}`);
    lines.push(`param.receiver.as2.own.id={{AS2_OWN_ID}}`);
    lines.push(`param.receiver.as2.signing.credential={{AS2_SIGNING_ALIAS}}`);
    lines.push(`param.receiver.as2.encryption.credential={{AS2_ENCRYPTION_ALIAS}}`);
  } else if (primaryConnector.includes('SFTP') || (connTypes || []).some(c => String(c).includes('SFTP'))) {
    lines.push(`param.receiver.sftp.host={{TARGET_SFTP_HOST}}`);
    lines.push(`param.receiver.sftp.port=22`);
    lines.push(`param.receiver.sftp.directory=/inbound/${artifact.domain?.toLowerCase() || 'data'}`);
    lines.push(`param.receiver.sftp.credential.alias={{TARGET_SFTP_CREDENTIAL_ALIAS}}`);
  } else if (primaryConnector.includes('JDBC') || (connTypes || []).some(c => String(c).includes('JDBC'))) {
    lines.push(`param.receiver.jdbc.datasource={{JDBC_DATASOURCE_ALIAS}}`);
    lines.push(`param.receiver.jdbc.schema={{DB_SCHEMA}}`);
  } else if (primaryConnector.includes('SUCCESSFACTORS') || (connTypes || []).some(c => String(c).includes('SuccessFactors'))) {
    lines.push(`param.receiver.sf.address=https://{{SFSF_HOST}}.successfactors.com`);
    lines.push(`param.receiver.sf.company.id={{SFSF_COMPANY_ID}}`);
    lines.push(`param.receiver.sf.credential.alias={{SFSF_CREDENTIAL_ALIAS}}`);
  } else {
    lines.push(`param.receiver.http.address={{TARGET_SYSTEM_URL}}`);
    lines.push(`param.receiver.http.credential.alias={{TARGET_CREDENTIAL_ALIAS}}`);
  }
  lines.push(``);

  // ── General params
  lines.push(`# --- General Settings ---`);
  lines.push(`param.log.level=INFO`);
  lines.push(`param.error.alert.email={{ALERT_EMAIL}}`);
  lines.push(`param.environment=${process.env.NODE_ENV === 'production' ? 'prod' : 'dev'}`);

  if ((artifact.maps_count || 0) > 0) {
    lines.push(``);
    lines.push(`# --- Mapping Parameters ---`);
    for (let i = 1; i <= artifact.maps_count; i++) {
      lines.push(`param.mapping.${i}.source.schema={{MAPPING_${i}_SOURCE_XSD}}`);
      lines.push(`param.mapping.${i}.target.schema={{MAPPING_${i}_TARGET_XSD}}`);
    }
  }

  if (artifact.has_scripting) {
    lines.push(``);
    lines.push(`# --- Script Parameters ---`);
    lines.push(`param.script.business.date.format=yyyy-MM-dd`);
    lines.push(`param.script.decimal.separator=.`);
    lines.push(`param.script.encoding=UTF-8`);
  }

  return lines.join('\n') + '\n';
}

// ── Message Mapping (.mmap) ───────────────────────────────────────────────────

function buildMessageMappings(artifact, pd) {
  const maps = [];
  const mapDescriptions = pd.mapDescriptions || pd.dataWeaveTransforms?.map(t => t.name) || [];
  const count = artifact.maps_count || 1;

  for (let i = 0; i < count; i++) {
    const mapDesc = mapDescriptions[i] || `${artifact.name}_Mapping_${i + 1}`;
    const safeId  = mapDesc.replace(/[^a-zA-Z0-9_]/g, '_');
    const filename = `${safeId}.mmap`;

    const content = buildMmapXML(artifact, safeId, mapDesc, i, pd);
    maps.push({ filename, content, id: safeId, label: mapDesc });
  }
  return maps;
}

function buildMmapXML(artifact, mapId, mapLabel, idx, pd) {
  const srcNs = artifact.platform === 'pipo' ? (pd.namespace || 'urn:sap.com:xi:example') : `urn:${(artifact.platform || 'source').toLowerCase()}:${(artifact.domain || 'INT').toLowerCase()}`;
  const tgtNs = `urn:sap.com:is:target:${(artifact.domain || 'INT').toLowerCase()}`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<MessageMapping xmlns="http://www.sap.com/xi/mapping/table" Version="1.0">
  <Heading>
    <Name>${mapId}</Name>
    <Namespace>${tgtNs}</Namespace>
    <SWCVersion></SWCVersion>
    <Description>Message mapping migrated from ${(artifact.platform || 'source').toUpperCase()} — ${mapLabel}</Description>
    <Responsible>IS Migration Tool (Sierra Digital)</Responsible>
    <LastChangedBy>is-migration-tool</LastChangedBy>
    <MappingTemplateReference>0</MappingTemplateReference>
  </Heading>
  <Interface type="source">
    <MessageType xmlns:src="${srcNs}" name="src:${artifact.name}_Input${idx > 0 ? '_' + idx : ''}"/>
  </Interface>
  <Interface type="target">
    <MessageType xmlns:tgt="${tgtNs}" name="tgt:${artifact.name}_Output${idx > 0 ? '_' + idx : ''}"/>
  </Interface>
  <!-- TODO: Import XSD schemas and define field mappings in IS Message Mapping editor -->
  <!-- Source XSD: Register schema for ${artifact.name} source message structure       -->
  <!-- Target XSD: Register schema for ${artifact.name} target message structure       -->
  <!--                                                                                   -->
  <!-- Field mapping stubs (add via IS Integration Designer drag-and-drop):              -->
${buildFieldMappingComments(artifact, pd, idx)}
</MessageMapping>
`;
}

function buildFieldMappingComments(artifact, pd, idx) {
  const transforms = pd.dataWeaveTransforms || [];
  const transform  = transforms[idx] || {};
  const fields     = transform.fieldMappings || [];

  if (!fields.length) {
    return `  <!-- No automatic field mapping data available — create manually in IS designer -->`;
  }

  return fields.slice(0, 15).map(f => {
    const [src, tgt] = f.split(' -> ');
    return `  <!-- Map: ${(src || f).trim()} -> ${(tgt || 'TARGET_FIELD').trim()} -->`;
  }).join('\n');
}

// ── Groovy Scripts ────────────────────────────────────────────────────────────

function buildGroovyScripts(artifact, pd) {
  const scripts = [];
  const srcScripts = pd.scripts || [];
  const platform = (artifact.platform || 'boomi').toLowerCase();

  if (srcScripts.length > 0) {
    srcScripts.forEach((s, i) => {
      const name     = (typeof s === 'string' ? s : s.name) || `Script_${i + 1}`;
      const safeId   = name.replace(/[^a-zA-Z0-9_]/g, '_');
      const filename = `${safeId}.groovy`;
      scripts.push({ filename, content: buildGroovyContent(artifact, name, safeId, platform, s, i) });
    });
  } else {
    // Fallback — one generic script stub
    const name = `${artifact.name}_Script`.replace(/[^a-zA-Z0-9_]/g, '_');
    scripts.push({
      filename: `${name}.groovy`,
      content: buildGroovyContent(artifact, name, name, platform, null, 0)
    });
  }

  return scripts;
}

function buildGroovyContent(artifact, scriptName, safeId, platform, scriptMeta, idx) {
  const purpose = getPurposeComment(scriptName, platform);
  const isDataWeave = platform === 'mulesoft' && scriptMeta?.type === 'dataweave';

  return `/**
 * Script: ${scriptName}
 * Artifact: ${artifact.name}
 * Domain: ${artifact.domain || 'INT'}
 * Source Platform: ${platform.toUpperCase()}
 * Migration Status: STUB — Business logic requires manual translation
 *
 * Purpose: ${purpose}
${isDataWeave ? ` * NOTE: This was originally a DataWeave 2.0 expression in MuleSoft.\n *       DataWeave logic must be manually re-implemented in Groovy or\n *       converted to SAP IS Message Mapping functions.` : ` * NOTE: This was originally a ${getPlatformScriptType(platform)} script.\n *       Review source logic and re-implement in Groovy for SAP IS.`}
 *
 * Groovy Script API References:
 *   com.sap.gateway.ip.core.customdev.util.Message
 *   com.sap.it.api.securestore.SecureStoreService
 *   com.sap.it.api.ITApiFactory
 */

import com.sap.gateway.ip.core.customdev.util.Message
import java.util.HashMap

def Message processData(Message message) {

    // ── Access message body ───────────────────────────────────────────────────
    def body = message.getBody(java.lang.String.class)

    // ── Access message headers ────────────────────────────────────────────────
    def headers = message.getHeaders()

    // ── Access message properties ─────────────────────────────────────────────
    def properties = message.getProperties()

    //
    // TODO: Implement business logic migrated from ${platform.toUpperCase()} ${getPlatformScriptType(platform)}
    //
    // Original source artifact: ${artifact.name}
    // Script index: ${idx + 1}
    // Domain: ${artifact.domain || 'INT'}
    //
${buildScriptTodoBlock(scriptName, artifact, platform, scriptMeta)}

    // ── Set modified body ─────────────────────────────────────────────────────
    message.setBody(body)

    return message
}
`;
}

function buildScriptTodoBlock(scriptName, artifact, platform, meta) {
  const name = scriptName.toLowerCase();
  const lines = [];

  if (name.includes('duplicate') || name.includes('idempotency')) {
    lines.push(`    // Duplicate/idempotency check logic`);
    lines.push(`    // Suggested: use IS JMS or JDBC idempotent receiver pattern`);
    lines.push(`    // def msgId = headers['MessageId'] ?: properties['CamelCorrelationId']`);
    lines.push(`    // Check store: com.sap.it.api.ITApiFactory.getService(IdempotentRepository.class)`);
  } else if (name.includes('transform') || name.includes('mapping') || name.includes('convert')) {
    lines.push(`    // Data transformation logic`);
    lines.push(`    // Tip: Complex field transformations may be better handled in IS Message Mapping`);
    lines.push(`    // def xml = new XmlSlurper().parseText(body)`);
    lines.push(`    // def result = new groovy.xml.MarkupBuilder(new StringWriter())`);
  } else if (name.includes('enrich') || name.includes('lookup')) {
    lines.push(`    // Data enrichment / lookup logic`);
    lines.push(`    // Example: JDBC lookup via externalized datasource`);
    lines.push(`    // message.setProperty('enrichedField', lookupValue)`);
  } else if (name.includes('validate') || name.includes('check')) {
    lines.push(`    // Validation logic`);
    lines.push(`    // Example: throw exception to route to error handling`);
    lines.push(`    // if (!isValid) throw new Exception('Validation failed: ' + reason)`);
  } else if (name.includes('route') || name.includes('filter')) {
    lines.push(`    // Routing / filtering logic`);
    lines.push(`    // Set routing properties consumed by IS Router step`);
    lines.push(`    // message.setProperty('routeCondition', evaluateCondition(body))`);
  } else {
    lines.push(`    // General script logic — translate from ${platform.toUpperCase()} source`);
    lines.push(`    // Review original ${getPlatformScriptType(platform)} and translate patterns to Groovy`);
  }

  if (artifact.domain === 'Finance') {
    lines.push(`    // Finance domain: ensure decimal precision with BigDecimal (not double)`);
  } else if (artifact.domain === 'HR') {
    lines.push(`    // HR domain: handle PII data carefully — do NOT log sensitive fields`);
  } else if (artifact.domain === 'Supply Chain') {
    lines.push(`    // Supply Chain: validate EDI segment counts and control numbers if applicable`);
  }

  return lines.join('\n');
}

function getPlatformScriptType(platform) {
  const map = { boomi: 'Groovy/JavaScript', mulesoft: 'DataWeave 2.0', pipo: 'Java/XSLT UDF', tibco: 'Java/BW Activity' };
  return map[platform] || 'script';
}

function getPurposeComment(scriptName, platform) {
  const name = scriptName.toLowerCase();
  if (name.includes('duplicate'))  return 'Duplicate detection / idempotency check';
  if (name.includes('transform'))  return 'Data transformation and field mapping';
  if (name.includes('validate'))   return 'Payload validation and business rule enforcement';
  if (name.includes('enrich'))     return 'Data enrichment from secondary source';
  if (name.includes('route'))      return 'Dynamic routing condition evaluation';
  if (name.includes('build'))      return 'Message structure builder / assembler';
  if (name.includes('parse'))      return 'Custom message parser';
  if (name.includes('log'))        return 'Custom logging and audit trail';
  return `Business logic migrated from ${platform.toUpperCase()}`;
}

// ── Main iFlow BPMN2 XML ──────────────────────────────────────────────────────

function buildIFlowXML(artifact, pd, conv, iflowId, iflowName) {
  const platform     = (artifact.platform || 'boomi').toLowerCase();
  const trigType     = artifact.trigger_type || 'API';
  const hasMaps      = (artifact.maps_count || 0) > 0;
  const hasScripts   = artifact.has_scripting;
  const hasErrors    = artifact.error_handling !== 'none' && artifact.error_handling;
  const connTypes    = pd.connectorTypes || pd.iflowAdapters || [];

  // Use iflow_xml from conversion output if available (Sprint 1 generated it)
  if (conv && conv.iflow_xml && conv.iflow_xml.includes('bpmn2:definitions')) {
    return enrichConversionXML(conv.iflow_xml, iflowId, iflowName, artifact);
  }

  // Build from scratch if no conversion output
  return buildFullBPMN(artifact, pd, iflowId, iflowName, platform, trigType, hasMaps, hasScripts, hasErrors, connTypes);
}

function enrichConversionXML(xml, iflowId, iflowName, artifact) {
  // Inject proper IDs and IS-specific attributes that the conversion engine may have used as placeholders
  return xml
    .replace(/id="[^"]*_iFlow_v1"/g, `id="${iflowId}"`)
    .replace(/<bpmn2:definitions /,
      `<bpmn2:definitions `)
    .replace(/<!-- Generated by IS Migration Tool -->/, `<!-- Generated by IS Migration Tool — Sierra Digital\n     iFlow: ${iflowName}\n     Source: ${(artifact.platform || '').toUpperCase()}\n     Package Version: 1.0.0 -->`);
}

function buildFullBPMN(artifact, pd, iflowId, iflowName, platform, trigType, hasMaps, hasScripts, hasErrors, connTypes) {
  const senderAdapter  = mapSenderAdapter(trigType, platform, connTypes);
  const receiverAdapter = mapReceiverAdapter(artifact, platform, connTypes);
  const domain = artifact.domain || 'INT';

  // Build process steps
  const steps = [];
  let yPos = 180;

  // Content Modifier at start
  steps.push(buildContentModifierStep('cm_start', 'Set Context Headers', 'CM_START', yPos, false));
  yPos += 80;

  // Mapping step(s)
  if (hasMaps) {
    for (let i = 0; i < Math.min(artifact.maps_count, 3); i++) {
      const mapId = `msg_map_${i + 1}`;
      const mapName = `Map_${i + 1}_${domain}`;
      steps.push(buildMappingStep(mapId, mapName, `MAP_${i + 1}`, yPos));
      yPos += 80;
    }
  }

  // Script step
  if (hasScripts) {
    const scriptName = (pd.scripts && pd.scripts[0])
      ? (typeof pd.scripts[0] === 'string' ? pd.scripts[0] : pd.scripts[0].name)
      : `${artifact.name}_Script`;
    const safeName = scriptName.replace(/[^a-zA-Z0-9_]/g, '_');
    steps.push(buildScriptStep(`script_1`, safeName, `SCRIPT_1`, yPos));
    yPos += 80;
  }

  // Content Modifier before send
  steps.push(buildContentModifierStep('cm_end', 'Set Response Headers', 'CM_END', yPos, false));
  yPos += 80;

  const processStepsXML = steps.join('\n      ');

  // Exception subprocess
  const exceptionXML = hasErrors ? buildExceptionSubprocess(artifact, iflowId) : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL"
    xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
    xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
    xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
    xmlns:ifl="http:///com.sap.ifl.model/Ifl.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    id="${iflowId}"
    targetNamespace="http://www.sap.com/${iflowId}">

  <!-- ══════════════════════════════════════════════════════════════════════════
       iFlow: ${iflowName}
       Source: ${platform.toUpperCase()} — ${artifact.name}
       Domain: ${domain} | Complexity: ${artifact.complexity_level || 'Medium'}
       Generated: ${new Date().toISOString()}
       Sierra Digital — IS Migration Tool
  ══════════════════════════════════════════════════════════════════════════ -->

  <bpmn2:collaboration id="Collaboration_${iflowId}" name="${iflowName}">

    <!-- ── Sender Channel ─────────────────────────────────────────────────── -->
    <bpmn2:participant id="Sender" name="Sender" ifl:type="ExternalSender">
      <bpmn2:extensionElements>
        <ifl:property>
          <key>enableBasicAuthCredentials</key><value>true</value>
        </ifl:property>
      </bpmn2:extensionElements>
    </bpmn2:participant>

    <!-- ── Integration Process ────────────────────────────────────────────── -->
    <bpmn2:participant id="Process_${iflowId}" name="${iflowName}" processRef="IntegrationProcess_${iflowId}">
    </bpmn2:participant>

    <!-- ── Receiver Channel ───────────────────────────────────────────────── -->
    <bpmn2:participant id="Receiver" name="Receiver" ifl:type="ExternalReceiver">
      <bpmn2:extensionElements>
        ${buildReceiverExtensions(artifact, platform, connTypes)}
      </bpmn2:extensionElements>
    </bpmn2:participant>

    <!-- ── Message Flows ──────────────────────────────────────────────────── -->
    <bpmn2:messageFlow id="MF_Sender_To_Process" sourceRef="Sender" targetRef="StartEvent_${iflowId}"
        name="${senderAdapter.adapterType}" ifl:type="senderChannel">
      <bpmn2:extensionElements>
        ${buildSenderChannelExtensions(senderAdapter, artifact)}
      </bpmn2:extensionElements>
    </bpmn2:messageFlow>
    <bpmn2:messageFlow id="MF_Process_To_Receiver" sourceRef="EndEvent_${iflowId}" targetRef="Receiver"
        name="${receiverAdapter.adapterType}" ifl:type="receiverChannel">
      <bpmn2:extensionElements>
        ${buildReceiverChannelExtensions(receiverAdapter, artifact)}
      </bpmn2:extensionElements>
    </bpmn2:messageFlow>
  </bpmn2:collaboration>

  <!-- ── Integration Process Definition ────────────────────────────────────── -->
  <bpmn2:process id="IntegrationProcess_${iflowId}" name="${iflowName}" isExecutable="true">

    <!-- Start Event -->
    <bpmn2:startEvent id="StartEvent_${iflowId}" name="Start">
      <bpmn2:outgoing>SEQ_Start_First</bpmn2:outgoing>
    </bpmn2:startEvent>

    ${processStepsXML}

    <!-- End Event -->
    <bpmn2:endEvent id="EndEvent_${iflowId}" name="End">
      <bpmn2:incoming>SEQ_Last_End</bpmn2:incoming>
    </bpmn2:endEvent>

    <!-- Sequence Flows -->
    ${buildSequenceFlows(iflowId, steps)}

    ${exceptionXML}

  </bpmn2:process>

  <!-- ── Diagram (BPMNDI) ───────────────────────────────────────────────────── -->
  <bpmndi:BPMNDiagram id="BPMNDiagram_${iflowId}">
    <bpmndi:BPMNPlane id="BPMNPlane_${iflowId}" bpmnElement="Collaboration_${iflowId}">
      <!-- Layout auto-generated by IS Migration Tool — open in IS Integration Designer to arrange -->
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>

</bpmn2:definitions>
`;
}

// ── BPMN Step Builders ────────────────────────────────────────────────────────

function buildContentModifierStep(id, name, label, yPos, isProperty) {
  return `<bpmn2:serviceTask id="${id}" name="${name}" ifl:type="ContentModifier">
      <bpmn2:extensionElements>
        <ifl:property><key>wrapperElement</key><value>root</value></ifl:property>
        <ifl:property><key>action</key><value>Create</value></ifl:property>
        <ifl:property><key>dataStoreLocation</key><value>Message Header</value></ifl:property>
        <ifl:property><key>name</key><value>X-Migration-Tool</value></ifl:property>
        <ifl:property><key>type</key><value>expression</value></ifl:property>
        <ifl:property><key>value</key><value>IS-Migration-v1.0</value></ifl:property>
      </bpmn2:extensionElements>
      <bpmn2:incoming>SEQ_To_${label}</bpmn2:incoming>
      <bpmn2:outgoing>SEQ_From_${label}</bpmn2:outgoing>
    </bpmn2:serviceTask>`;
}

function buildMappingStep(id, name, label, yPos) {
  return `<bpmn2:serviceTask id="${id}" name="${name}" ifl:type="MessageMapping">
      <bpmn2:extensionElements>
        <ifl:property><key>mappingName</key><value>${name}</value></ifl:property>
        <ifl:property><key>archiveFileRef</key><value>ref:${name}.mmap</value></ifl:property>
        <ifl:property><key>operationName</key><value>Operation1</value></ifl:property>
      </bpmn2:extensionElements>
      <bpmn2:incoming>SEQ_To_${label}</bpmn2:incoming>
      <bpmn2:outgoing>SEQ_From_${label}</bpmn2:outgoing>
    </bpmn2:serviceTask>`;
}

function buildScriptStep(id, scriptName, label, yPos) {
  return `<bpmn2:serviceTask id="${id}" name="${scriptName}" ifl:type="ScriptActivity">
      <bpmn2:extensionElements>
        <ifl:property><key>script</key><value>ref:${scriptName}.groovy</value></ifl:property>
        <ifl:property><key>scriptLanguage</key><value>groovy</value></ifl:property>
      </bpmn2:extensionElements>
      <bpmn2:incoming>SEQ_To_${label}</bpmn2:incoming>
      <bpmn2:outgoing>SEQ_From_${label}</bpmn2:outgoing>
    </bpmn2:serviceTask>`;
}

function buildSequenceFlows(iflowId, steps) {
  if (!steps.length) {
    return `<bpmn2:sequenceFlow id="SEQ_Start_First" sourceRef="StartEvent_${iflowId}" targetRef="EndEvent_${iflowId}" name=""/>`;
  }

  const flows = [];
  const ids = steps.map(s => {
    const match = s.match(/id="([^"]+)"/);
    return match ? match[1] : null;
  }).filter(Boolean);

  // Start → first
  flows.push(`<bpmn2:sequenceFlow id="SEQ_Start_First" sourceRef="StartEvent_${iflowId}" targetRef="${ids[0]}" name=""/>`);

  // Step → step
  for (let i = 0; i < ids.length - 1; i++) {
    flows.push(`<bpmn2:sequenceFlow id="SEQ_${ids[i]}_${ids[i+1]}" sourceRef="${ids[i]}" targetRef="${ids[i+1]}" name=""/>`);
  }

  // Last → end
  flows.push(`<bpmn2:sequenceFlow id="SEQ_Last_End" sourceRef="${ids[ids.length - 1]}" targetRef="EndEvent_${iflowId}" name=""/>`);

  return flows.join('\n    ');
}

function buildExceptionSubprocess(artifact, iflowId) {
  const multiCatch = artifact.error_handling === 'multi_try_catch';
  return `<!-- ── Exception Subprocess ──────────────────────────────────────────── -->
    <bpmn2:subProcess id="ExceptionSubprocess_${iflowId}" name="Exception Subprocess" triggeredByEvent="true">
      <bpmn2:extensionElements>
        <ifl:property><key>activityType</key><value>ExceptionSubProcess</value></ifl:property>
      </bpmn2:extensionElements>
      <bpmn2:startEvent id="ErrorStart_${iflowId}" name="Error Start">
        <bpmn2:errorEventDefinition errorRef="ErrorDef_${iflowId}"/>
        <bpmn2:outgoing>SEQ_ErrStart_Alert</bpmn2:outgoing>
      </bpmn2:startEvent>
      <bpmn2:serviceTask id="Alert_${iflowId}" name="Send Error Alert" ifl:type="send">
        <bpmn2:extensionElements>
          <ifl:property><key>targetChannel</key><value>alertChannel</value></ifl:property>
          <ifl:property><key>alertSubject</key><value>iFlow Error: ${artifact.name}</value></ifl:property>
          <ifl:property><key>alertBody</key><value>Error in ${artifact.name}: $\{exception.message\}</value></ifl:property>
        </bpmn2:extensionElements>
        <bpmn2:incoming>SEQ_ErrStart_Alert</bpmn2:incoming>
        <bpmn2:outgoing>SEQ_Alert_End</bpmn2:outgoing>
      </bpmn2:serviceTask>
      <bpmn2:endEvent id="ErrorEnd_${iflowId}" name="Error End">
        <bpmn2:errorEventDefinition/>
        <bpmn2:incoming>SEQ_Alert_End</bpmn2:incoming>
      </bpmn2:endEvent>
      <bpmn2:sequenceFlow id="SEQ_ErrStart_Alert" sourceRef="ErrorStart_${iflowId}" targetRef="Alert_${iflowId}"/>
      <bpmn2:sequenceFlow id="SEQ_Alert_End" sourceRef="Alert_${iflowId}" targetRef="ErrorEnd_${iflowId}"/>
    </bpmn2:subProcess>
    <bpmn2:error id="ErrorDef_${iflowId}" name="ProcessError" errorCode="IS_MIGRATION_ERROR"/>`;
}

// ── Adapter Builders ──────────────────────────────────────────────────────────

function mapSenderAdapter(trigType, platform, connTypes) {
  if (trigType === 'Schedule') return { adapterType: 'Timer', component: 'timer' };
  if (trigType === 'Event')    return { adapterType: 'JMS', component: 'jms' };
  if (trigType === 'Listener') {
    if ((connTypes || []).some(c => String(c).includes('AS2'))) return { adapterType: 'AS2', component: 'as2' };
    return { adapterType: 'SFTP', component: 'sftp' };
  }
  return { adapterType: 'HTTPS', component: 'https' };
}

function mapReceiverAdapter(artifact, platform, connTypes) {
  const conn = (artifact.primary_connector || '').toUpperCase();
  if (conn.includes('RFC') || (connTypes || []).some(c => String(c).includes('RFC'))) return { adapterType: 'RFC', component: 'rfc' };
  if ((connTypes || []).some(c => String(c).includes('IDoc')))                         return { adapterType: 'IDoc', component: 'idoc' };
  if ((connTypes || []).some(c => String(c).includes('AS2')))                          return { adapterType: 'AS2', component: 'as2' };
  if (conn.includes('SALESFORCE') || (connTypes || []).some(c => String(c).includes('Salesforce')))  return { adapterType: 'Salesforce', component: 'salesforce' };
  if (conn.includes('SUCCESSFACTORS') || (connTypes || []).some(c => String(c).includes('SuccessFactors'))) return { adapterType: 'SuccessFactors', component: 'successfactors' };
  if (conn.includes('SFTP') || (connTypes || []).some(c => String(c).includes('SFTP'))) return { adapterType: 'SFTP', component: 'sftp' };
  if (conn.includes('JDBC') || (connTypes || []).some(c => String(c).includes('JDBC'))) return { adapterType: 'JDBC', component: 'jdbc' };
  if (conn.includes('ARIBA') || (connTypes || []).some(c => String(c).includes('Ariba')))  return { adapterType: 'Ariba', component: 'ariba' };
  if ((connTypes || []).some(c => String(c).includes('Kafka')))  return { adapterType: 'Kafka', component: 'kafka' };
  if ((connTypes || []).some(c => String(c).includes('Mail')))   return { adapterType: 'Mail', component: 'mail' };
  return { adapterType: 'HTTP', component: 'http' };
}

function buildSenderChannelExtensions(adapter, artifact) {
  if (adapter.component === 'https') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericSenderBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>https</value></ifl:property>
        <ifl:property><key>address</key><value>{{param.sender.address}}</value></ifl:property>
        <ifl:property><key>authType</key><value>{{param.sender.auth.type}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.sender.credential.alias}}</value></ifl:property>
        <ifl:property><key>httpMethod</key><value>POST</value></ifl:property>`;
  }
  if (adapter.component === 'timer') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericSenderBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>timer</value></ifl:property>
        <ifl:property><key>schedulerCron</key><value>{{param.scheduler.cron}}</value></ifl:property>
        <ifl:property><key>schedulerTimeZone</key><value>{{param.scheduler.timezone}}</value></ifl:property>`;
  }
  if (adapter.component === 'sftp') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericSenderBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>sftp</value></ifl:property>
        <ifl:property><key>host</key><value>{{param.sftp.host}}</value></ifl:property>
        <ifl:property><key>port</key><value>{{param.sftp.port}}</value></ifl:property>
        <ifl:property><key>directory</key><value>{{param.sftp.directory}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.sftp.credential.alias}}</value></ifl:property>`;
  }
  if (adapter.component === 'jms') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericSenderBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>jms</value></ifl:property>
        <ifl:property><key>connectionFactory</key><value>{{param.jms.connection.factory}}</value></ifl:property>
        <ifl:property><key>queueName</key><value>{{param.jms.queue.name}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.jms.credential.alias}}</value></ifl:property>`;
  }
  return `<ifl:property><key>ComponentType</key><value>IflGenericSenderBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>${adapter.component}</value></ifl:property>`;
}

function buildReceiverExtensions(artifact, platform, connTypes) {
  return `<ifl:property><key>ComponentType</key><value>ExternalSystem</value></ifl:property>`;
}

function buildReceiverChannelExtensions(adapter, artifact) {
  if (adapter.component === 'http') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>http</value></ifl:property>
        <ifl:property><key>address</key><value>{{param.receiver.http.address}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.receiver.http.credential.alias}}</value></ifl:property>
        <ifl:property><key>httpMethod</key><value>POST</value></ifl:property>`;
  }
  if (adapter.component === 'rfc') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>rfc</value></ifl:property>
        <ifl:property><key>rfcHost</key><value>{{param.receiver.sap.rfc.host}}</value></ifl:property>
        <ifl:property><key>rfcSystemNumber</key><value>{{param.receiver.sap.rfc.system.number}}</value></ifl:property>
        <ifl:property><key>rfcClient</key><value>{{param.receiver.sap.rfc.client}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.receiver.sap.credential.alias}}</value></ifl:property>`;
  }
  if (adapter.component === 'idoc') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>idoc</value></ifl:property>
        <ifl:property><key>rfcHost</key><value>{{param.receiver.idoc.sap.host}}</value></ifl:property>
        <ifl:property><key>rfcClient</key><value>{{param.receiver.idoc.sap.client}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.receiver.idoc.sap.credential.alias}}</value></ifl:property>`;
  }
  if (adapter.component === 'sftp') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>sftp</value></ifl:property>
        <ifl:property><key>host</key><value>{{param.receiver.sftp.host}}</value></ifl:property>
        <ifl:property><key>port</key><value>{{param.receiver.sftp.port}}</value></ifl:property>
        <ifl:property><key>directory</key><value>{{param.receiver.sftp.directory}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.receiver.sftp.credential.alias}}</value></ifl:property>`;
  }
  if (adapter.component === 'salesforce') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>salesforce</value></ifl:property>
        <ifl:property><key>address</key><value>{{param.receiver.salesforce.address}}</value></ifl:property>
        <ifl:property><key>credential.name</key><value>{{param.receiver.salesforce.oauth.credential.alias}}</value></ifl:property>`;
  }
  if (adapter.component === 'as2') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>as2</value></ifl:property>
        <ifl:property><key>address</key><value>{{param.receiver.as2.url}}</value></ifl:property>
        <ifl:property><key>as2From</key><value>{{param.receiver.as2.own.id}}</value></ifl:property>
        <ifl:property><key>as2To</key><value>{{param.receiver.as2.partner.id}}</value></ifl:property>
        <ifl:property><key>signingPrivateKey</key><value>{{param.receiver.as2.signing.credential}}</value></ifl:property>`;
  }
  if (adapter.component === 'jdbc') {
    return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>jdbc</value></ifl:property>
        <ifl:property><key>dataSource</key><value>{{param.receiver.jdbc.datasource}}</value></ifl:property>
        <ifl:property><key>schema</key><value>{{param.receiver.jdbc.schema}}</value></ifl:property>`;
  }
  return `<ifl:property><key>ComponentType</key><value>IflGenericReceiverBean</value></ifl:property>
        <ifl:property><key>adapterType</key><value>${adapter.component}</value></ifl:property>
        <ifl:property><key>address</key><value>{{param.receiver.http.address}}</value></ifl:property>`;
}

// ── Name / ID helpers ─────────────────────────────────────────────────────────

function buildIFlowId(artifact) {
  const parts = (artifact.name || 'Process').replace(/[^a-zA-Z0-9_]/g, '_').split('_').filter(Boolean);
  return `${artifact.domain || 'INT'}_${parts.slice(0, 4).join('_')}_iFlow_v1`;
}

function buildIFlowName(artifact) {
  return buildIFlowId(artifact).replace(/_/g, ' ').replace(' v1', ' v1.0');
}

function buildPackageName(artifact) {
  return `${artifact.domain || 'INT'}_Migration_Package_v1`;
}

module.exports = { generateIFlowPackage, buildIFlowId, buildIFlowName, buildPackageName };
